### ISSUE TITLE
下面5个键无法设置

### ISSUE THREAD

**Issue by clansty** [Archeb/Aqours#1]
下面推特fb谷歌几个键无法设置连接

**Comment by Archeb** [comment]
在default.hbs中的第48-52行：
`<a href="twitter地址" class="button cycle-button ribbed-blue" style="color:white"><span class="mif-twitter icon"></span></a>`
        `<a href="g+地址" class="button cycle-button ribbed-red" style="color:white"><span class="mif-google-plus icon"></span></a>`
        `<a href="fb地址" class="button cycle-button ribbed-yellow" style="color:white"><span class="mif-facebook icon"></span></a>`
        `<a href="github地址" class="button cycle-button ribbed-white"><span class="mif-github icon"></span></a>`
        `<a href="steam地址" class="button cycle-button ribbed-green"><span class="mif-steam icon"></span></a>`

**Comment by clansty** [comment]
好的，谢谢
